CREATE DATABASE riquinho;
USE riquinho;


CREATE TABLE IF NOT EXISTS USUARIO
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CONSTRAINT USUARIO_PKEY PRIMARY KEY (id),
    CONSTRAINT USUARIO_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS CARTEIRA
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ID_USUARIO INT NOT NULL,
    SALDO INT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CONSTRAINT CARTEIRA_PKEY PRIMARY KEY (id),
    CONSTRAINT USUARIO_ID_CARTEIRA FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS TRANSACOES
(
    ID INT NOT NULL AUTO_INCREMENT,
    ID_CARTEIRA INT NOT NULL,
    SALDO_ANTERIOR INT NOT NULL,
    SALDO_ATUAL INT NOT NULL,
    TIPO_TRANSA VARCHAR(255) NOT NULL,
    DATA_TRANSA DATETIME,
    VALOR_TRANSA INT NOT NULL,
    CONSTRAINT TRANSACOES_PKEY PRIMARY KEY (id),
    CONSTRAINT CARTEIRA_ID_TRANSACOES FOREIGN KEY (ID_CARTEIRA)
        REFERENCES CARTEIRA (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

