DROP DATABASE IF EXISTS riquinho;

CREATE DATABASE riquinho;

USE riquinho;


CREATE TABLE IF NOT EXISTS USUARIO
(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CONSTRAINT USUARIO_PKEY PRIMARY KEY (id),
    CONSTRAINT USUARIO_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS TRANSACOES
(
    ID INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    TIPO_TRANSA VARCHAR(255) NOT NULL,
    DATA_TRANSA DATETIME,
    VALOR_TRANSA INT NOT NULL,
    INFO VARCHAR(255) NOT NULL,
    CONSTRAINT TRANSACOES_PKEY PRIMARY KEY (id),
    CONSTRAINT USUARIO_ID_TRASACAO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

